---
- name: Configure data disks
  hosts: linux
  gather_facts: yes
  become: yes
  become_method: sudo

  roles:
    - datadisk-n01609389
    - profile-n01609389
    - user-n01609389
    - webserver-n01609389
